version: '3.8'
services:
  db:
    image: postgres:15
    container_name: postgres-smallbank
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mellon
      POSTGRES_DB: smallbank
    ports:
      - "5432:5432"
    networks:
      - smallbank-network

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - smallbank-network

networks:
  smallbank-network:
    driver: bridge